import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Footer from "@/components/footer/Footer";
import FooterContact from "@/components/footer/FooterContact";
import Navbar from "@/components/navbar/Navbar";
import NavbarInfo from "@/components/navbar/NavbarInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <NavbarInfo/>
          {children}
          <FooterContact />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
